[batch]
jobs = [
    "tenki",
    "usd",
    "usd-short",
    "usd-long",
    "bun",
    "taiju",
]

[job.date]
command = "./scripts/date"

[job.tenki]
command = "./scripts/tenki.sh"

[job.anical]
command = "./scripts/anime.sh"

[job.usd]
command = "./scripts/usd.sh"

[job.usd-short]
command = "./scripts/usd-short.sh"

[job.usd-long]
command = "./scripts/usd-long.sh"

[job.bun]
command = "./scripts/bun.sh"

[job.taiju]
command = "./scripts/taiju.sh"
